### Pandas

> Pandas is a powerfull python library for manipulation and alanaysis of data

> Its a open source library

>fast(built on top of numpy),flexible(different resource), productive library

Instal

Install

In [2541]:
! pip install pandas

Access is denied.

In [2542]:
import pandas as pd

In [2543]:
print(pd.__version__)

2.2.3

###Series - One dimentional array(data structure)with label

Series - One dimensional array(data structure)with label

l1 = [1,2,3,4,5]
type(1)

In [2544]:
l1 = [1,2,3,4,5]
type(l1)

list

In [2545]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2546]:
pd.Series(l1,name = "Series")

0    1
1    2
2    3
3    4
4    5
Name: Series, dtype: int64

In [2547]:
s= pd.Series(l1,index = ["a","b","c","d","e"],name = "My Series")

In [2548]:
s['a']

np.int64(1)

In [2549]:
type(s)

pandas.core.series.Series

Note: Index in Series are immutable(can change)

In [2550]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [2551]:
s.values

array([1, 2, 3, 4, 5])

In [2552]:
### changing the index of pandas series

s = s.rename(index = {'b':'y'})

In [2553]:
s

a    1
y    2
c    3
d    4
e    5
Name: My Series, dtype: int64

In [2554]:
s.rename(index = {'b':'y'},inplace = True)

# Dataframe - its a 2d array(just like tables)

In [2555]:
dict1 = {'name':['virat','rohit','dhoni','jadeja','bumrah'],
'age':[34,33,40,32,30],
'marks':[80,85,75,80,70],
'Role':['batsman','batsman','wicketkeeper','allrounder','bowler']}



pd.DataFrame(dict1)

     name  age  marks          Role
0   virat   34     80       batsman
1   rohit   33     85       batsman
2   dhoni   40     75  wicketkeeper
3  jadeja   32     80    allrounder
4  bumrah   30     70        bowler

In [2556]:
df = pd.DataFrame(dict1)

In [2557]:
type(df)

pandas.core.frame.DataFrame

In [2558]:
df.tail(2)

     name  age  marks        Role
3  jadeja   32     80  allrounder
4  bumrah   30     70      bowler

In [2559]:
df.head(2)

    name  age  marks     Role
0  virat   34     80  batsman
1  rohit   33     85  batsman

In [2560]:
len(df)

5

In [2561]:
df.count()

name     5
age      5
marks    5
Role     5
dtype: int64

In [2562]:
df.columns

Index(['name', 'age', 'marks', 'Role'], dtype='object')

In [2563]:
df['name']

0     virat
1     rohit
2     dhoni
3    jadeja
4    bumrah
Name: name, dtype: object

In [2564]:
type(df)

pandas.core.frame.DataFrame

In [2565]:
type(df['name'])

pandas.core.series.Series

In [2566]:
df['name'].value_counts()

name
virat     1
rohit     1
dhoni     1
jadeja    1
bumrah    1
Name: count, dtype: int64

### Basic operations

> Importing data set from different files

> Importing tabular dataset

In [2567]:
pd.read_csv(r"C:\Users\klemp\Desktop\Divya Anu\datasets\ETH_1h.csv")

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2568]:
stock_df = pd.read_csv(r"C:\Users\klemp\Desktop\Divya Anu\datasets\ETH_1h.csv")

In [2569]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

# top 5 rows

In [2570]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [2571]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

> bottom 5 rows

In [2572]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [2573]:
## Number of rows in dataframe
len(stock_df)

23674

 ## Access column names of dataframe

In [2574]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [2575]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2576]:
## accessing a column in a dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [2577]:
stock_df[['Date','Open','Low']]

                   Date    Open     Low
0      2020-03-13 08-PM  129.94  126.87
1      2020-03-13 07-PM  119.51  117.10
2      2020-03-13 06-PM  124.47  115.50
3      2020-03-13 05-PM  124.08  121.63
4      2020-03-13 04-PM  124.85  120.17
...                 ...     ...     ...
23669  2017-07-01 03-PM  265.74  265.00
23670  2017-07-01 02-PM  268.79  265.00
23671  2017-07-01 01-PM  274.83  265.00
23672  2017-07-01 12-PM  275.01  271.00
23673  2017-07-01 11-AM  279.98  272.10

[23674 rows x 3 columns]

## Accessing rows and dataframe

In [2578]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2579]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [2580]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [2581]:
[1,2,3,4,'hello',True]

[1, 2, 3, 4, 'hello', True]

## Accessing rows

In [2582]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [2583]:
stock_df.loc[23672,'Date']

'2017-07-01 12-PM'

In [2584]:
stock_df.loc[23672,['Date','Close','Open']]

Date     2017-07-01 12-PM
Close              274.83
Open               275.01
Name: 23672, dtype: object

In [2585]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [2586]:
l = [1,2,3,4,5]
l[1:4] # slicing a list

[2, 3, 4]

In [2587]:
d2 = [[1,2,3],
      [4,5,6],
      [7,8,9]]
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2588]:
d2[2][1]

8

In [2589]:
d2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#### Slicing in loc (labeled location)

df.loc['row_label_1':'row_label_3':'column_label_1':'column_label_2']

In [2590]:
stock_df.loc[23672,'Open':'Close']

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

In [2591]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2592]:
stock_df.iloc[1]

Date      2020-03-13 07-PM
Symbol              ETHUSD
Open                119.51
High                132.02
Low                  117.1
Close               129.94
Volume          7579741.09
Name: 1, dtype: object

In [2593]:
stock_df .iloc[1,2] # row index and column index

np.float64(119.51)

In [2594]:
stock_df .iloc[3,[2,4]] # multuple column index

Open    124.08
Low     121.63
Name: 3, dtype: object

In [2595]:
stock_df .iloc[2,5:6] # slicing of colmns using iloc

Close    119.51
Name: 2, dtype: object

In [2596]:
stock_df .iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

## Filtering

In [2597]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2598]:
stock_df['High']

0        131.82
1        132.02
2        124.85
3        127.42
4        129.51
          ...
23669    272.74
23670    269.90
23671    274.93
23672    275.01
23673    279.99
Name: High, Length: 23674, dtype: float64

In [2599]:
stock_df['High'] > 130

0         True
1         True
2        False
3        False
4        False
         ...
23669     True
23670     True
23671     True
23672     True
23673     True
Name: High, Length: 23674, dtype: bool

In [2600]:
f1 = stock_df['High'] > 130


stock_df[f1]

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
6      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

In [2601]:
f1 = stock_df['High'] > 130


stock_gt_130 = stock_df[f1]

In [2602]:
stock_gt_130.reset_index(drop=True,inplace=True)

In [2603]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

Adding new column

In [2604]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [2605]:
len(stock_df)

23674

In [2606]:
stock_df['Random_col'] = list(range(1,len(stock_df)+1))

In [2607]:
stock_df['Random_col']

0            1
1            2
2            3
3            4
4            5
         ...
23669    23670
23670    23671
23671    23672
23672    23673
23673    23674
Name: Random_col, Length: 23674, dtype: int64

Dropping column

In [2608]:
stock_df.drop(columns = ['Random_col'],inplace = True)

In [2609]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [2610]:
stock_df.drop(columns=['Open','High'],inplace=True)

In [2611]:
stock_df

                   Date  Symbol     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  120.17  124.08  4461424.71
...                 ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  272.10  275.01   679358.87

[23674 rows x 5 columns]

In [2612]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

Dropping rows